### Autostart applications ###

# Export Wayland env to systemd / dbus
exec_always dbus-update-activation-environment --systemd \
  WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

# Status bar
exec waybar

# Network tray (opcional)
exec nm-applet --indicator

# Policy kit (necessário para apps GUI pedirem senha)
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# DBus / systemd integration
exec_always dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

# Bluetooth
exec blueman-applet

exec_always gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
